Update database.md
koishijs/koishijs.github.io pull request #20
Opened 2021-04-17 15:49 UTC by H4M5TER

2021-04-17 19:24 UTC, Shigma requested changes
感谢，顺便那个 id 现在也是 string 了，能帮忙改下吗 QAQ

2021-04-18 20:37 UTC, H4M5TER commented
manage.md里面那个???到底是什么

2021-04-18 20:43 UTC, H4M5TER commented
另外，我觉得manage.md里观察者对象应该在数据库那章也提一嘴，提前声明字段应该直接放到指令系统那章。
我刚刚就想找提前声明字段，感觉之前看过然后找指令系统那章又没找到。

2021-04-19 07:07 UTC, Shigma approved these changes

2021-04-19 07:07 UTC, merged