Update admin.md
koishijs/koishijs.github.io pull request #50
Opened 2022-07-02 14:46 UTC by samnyan

2022-07-03 14:14 UTC, shigma requested changes

2022-07-03 14:14 UTC, shigma commented on plugins/accessibility/admin.md
> +- 基本语法：`authorize <value> -u @{platform}:{userId}`
这里实际上有两种用法：

- @someone，必须是实际的 @
- @{platform}:{userId}，必须是纯文本

大部分情况下，用户使用第一种语法就应该足够。不过我有点不知道如何表达比较好。

2022-07-03 17:27 UTC, samnyan commented on plugins/accessibility/admin.md
> +- 基本语法：`authorize <value> -u @{platform}:{userId}`
这里或许直接写成三种情况更清晰一点。(1) at人， (2) @user，(3) @platform:user 
我想了想第二种语法按道理要写成 `{@[<platform>:]<user>}`，但实在是复杂了点，带platform和不带的干脆分开好了。

2022-07-03 17:31 UTC, shigma commented on plugins/accessibility/admin.md
> +- 基本语法：`authorize <value> -u @{platform}:{userId}`
确实是三种，你可以分开写。

2022-07-04 12:29 UTC, shigma commented on plugins/accessibility/admin.md
> +- `@user`: 通过直接@人的方式指定
`@` 和中文之间加空格

```diff
- - `@user`: 通过直接@人的方式指定
+ - `@user`: 通过直接 @ 人的方式指定
```

2022-07-04 12:29 UTC, shigma commented on plugins/accessibility/admin.md
> +- `@user`: 通过直接@人的方式指定
感觉这里明确区分一下比较好？

- 通过直接 @ 人的方式指定 (不能是纯文本)
- @ 符号后面接用户名 (必须是纯文本)

2022-07-04 16:27 UTC, shigma approved these changes
下面注释里还有一个 @ 后面要加空格你漏了x

2022-07-04 16:28 UTC, shigma commented on plugins/accessibility/admin.md
> +  - `-u, --user [@user]` 目标用户（user.flag指令。需要 3 级权限）
```suggestion
  - `-u, --user [@user]` 目标用户（user.flag指令。需要 3 级权限）
  - `-u, --user [@user]` 目标用户（仅限 user.flag 指令，需要 3 级权限）
```

下一行同上。

2022-07-08 19:09 UTC, merged